all: pdf

clean:
	rm -f egu2012_poster.aux egu2012_poster.log pythonlisting.aux a0header.ps

pdf: egu2012_poster.tex
	pdflatex egu2012_poster.tex
	#bibtex egu2012_poster
	#pdflatex egu2012_poster.tex
